apps/cms/urls.py
from django.urls import path
from . import views
from . import course_views, straff_views

app_name = 'cms'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('write_news/', views.WirteNewsView.as_view(), name="write_news"),
    path('edit_news/', views.EditNewsView.as_view(), name="edit_news"),
    path('del_news/', views.del_news, name="del_news"),
    path('news_category/', views.NewsCategoryView.as_view(), name="news_category"),
    path('add_category/', views.add_category, name="add_category"),
    path('edit_category/', views.edit_category, name="edit_category"),
    path('del_category/', views.del_category, name="del"),
    path('upload/', views.upload_file, name="upload_file"),
    path('banner/', views.banners, name="banners"),
    path('banner_add/', views.banner_add, name="banner_add"),
    path('banner_list/', views.banner_list, name="banner_list"),
    path('banner_del/', views.banner_del, name="banner_del"),
    path('banner_edit/', views.banner_edit, name="banner_edit"),
    path('news_list/', views.NewsListView.as_view(), name="news_list"),
]

urlpatterns += [
    path('publish_course/', course_views.PublishCourseView.as_view(), name="publish_course"),
]

urlpatterns += [
    path('staff_view/', straff_views.StaffView.as_view(), name="staff_view"),
    path('staff_add_view/', straff_views.StaffAddView.as_view(), name="staff_add_view"),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('<int:news_id>/', views.NewsDteail.as_view(), name="news_detail"),
    path('news_list/', views.news_list, name="news_list"),
    path('comment/', views.comment, name="comment"),
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'
urlpatterns = [
    path('login/', views.login_view, name="login_view"),
    path('logout/', views.logout_view, name="logout_view"),
    path('signup/', views.signup_view, name="signup_view"),
    # 登录页面验证码图片请求
    path('get_valid_img/', views.GetValidImg.as_view(), name='get_valid_img'),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('news/', include("apps.news.urls")),
    path('cms/', include("apps.cms.urls")),
    path('account/', include("apps.xfzauth.urls")),
    path('course/', include("apps.course.urls")),
    path('controller/', include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/cms/models.py
from django.db import models

apps/course/models.py
from django.db import models

class CourseCategory(models.Model):
	name = models.CharField(max_length=20)

class Teacher(models.Model):
	name = models.CharField(max_length=20)
	avatar = models.URLField()
	jobtitle = models.CharField(max_length=100)
	perfile = models.TextField()

class Course(models.Model):
	title = models.CharField(max_length=100)
	category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
	teacher = models.ForeignKey('Teacher',on_delete=models.DO_NOTHING)
	video_url = models.URLField()
	cover_url = models.URLField()
	price = models.FloatField()
	duration = models.IntegerField() # 时长
	profile = models.TextField()
	pub_time = models.DateTimeField(auto_now_add=True)

apps/news/models.py
from django.db import models

class NewsCategory(models.Model):
	name = models.CharField(max_length=100)

class News(models.Model):
	title = models.CharField(max_length=100)
	desc = models.CharField(max_length=200)
	thumbnail = models.URLField()
	content = models.TextField()
	pub_time = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)
	category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
	class Meta:
		ordering = ['-pub_time']

class Comment(models.Model):
	content = models.TextField()
	pub_time = models.DateTimeField(auto_now_add=True)
	news = models.ForeignKey('News', on_delete=models.CASCADE, related_name='comments')
	author = models.ForeignKey('xfzauth.User', on_delete=models.CASCADE)
	class Meta:
		ordering = ["-pub_time"]

class Banner(models.Model):
	priority = models.IntegerField(default=0)
	image_url = models.URLField()
	link_to = models.URLField()
	pub_time = models.DateTimeField(auto_now_add=True)
	class Meta:
		ordering = ["-priority"]

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms
from apps.news.models import Banner, News

class BannerForm(forms.ModelForm, FormMixin):
	class Meta:
		model = Banner
		fields = ['priority', 'image_url', 'link_to']
		error_messages = {
			'priority':{'required':"请输入优先级！", "invalid": "优先级必须为数字！"},
			'image_url':{'required':"请上传轮播图！"},
			'link_to':{'required':"请输入跳转链接！","invalid": "跳转链接格式错误！"},
		}

class editBannerForm(forms.ModelForm, FormMixin):
	pk = forms.IntegerField()
	class Meta:
		model = Banner
		fields = ['priority', 'image_url', 'link_to']
		error_messages = {
			'priority':{'required':"请输入优先级！", "invalid": "优先级必须为数字！"},
			'image_url':{'required':"请上传轮播图！"},
			'link_to':{'required':"请输入跳转链接！","invalid": "跳转链接格式错误！"},
		}

class EditNewsForm(forms.ModelForm, FormMixin):
	category = forms.IntegerField()
	news_id = forms.IntegerField()
	class Meta:
		model = News
		fields = ['thumbnail', 'title', 'desc', 'content']

apps/cms/views.py
from django.shortcuts import render
from django.views import View
from apps.news.models import NewsCategory,News
from utils import restful
from django.views.decorators.http import require_POST
from apps.news.forms import EditCategory, WriteNewsForm
from django.conf import settings
import os
from .forms import BannerForm, editBannerForm, EditNewsForm
from apps.news.models import Banner
from apps.news.serializers import BannerSerializer
from django.utils.decorators import method_decorator
from apps.news.decorator.xfz_login_required import xfz_login_required, xfz_perms_change_required
from django.core.paginator import Paginator
from _datetime import datetime
from urllib import parse
from django.utils.timezone import make_aware



def index(request):
	return render(request, 'cms/index.html')

@method_decorator(xfz_perms_change_required, name='dispatch')
class WirteNewsView(View):
	def get(self,request):
		categories = NewsCategory.objects.all()
		return render(request, 'cms/write_news.html', {'categories':categories})
	def post(self,request):
		form = WriteNewsForm(request.POST)
		if form.is_valid():
			title = form.cleaned_data.get('title')
			desc = form.cleaned_data.get('desc')
			thumbnail = form.cleaned_data.get('thumbnail')
			content = form.cleaned_data.get('content')
			category_id = form.cleaned_data.get('category')
			category = NewsCategory.objects.get(pk=category_id)
			News.objects.create(title=title,desc=desc,thumbnail=thumbnail,
			                    content=content, category=category,author=request.user)
			return restful.ok()
		else:
			message = form.get_errors()
			print(message)
			restful.paramserror(message=message)

@method_decorator(xfz_perms_change_required, name='dispatch')
class EditNewsView(View):
	def get(self,request):
		news_id = request.GET.get('news_id')
		news = News.objects.select_related('category').get(pk=news_id)
		categories = NewsCategory.objects.all()
		return render(request, 'cms/write_news.html',{'news': news, 'categories': categories})

	def post(self, request):
		form = EditNewsForm(request.POST)
		if form.is_valid():
			title = form.cleaned_data.get('title')
			desc = form.cleaned_data.get('desc')
			thumbnail = form.cleaned_data.get('thumbnail')
			content = form.cleaned_data.get('content')
			category_id = form.cleaned_data.get('category')
			news_id = form.cleaned_data.get('news_id')
			category = NewsCategory.objects.get(pk=category_id)
			News.objects.filter(pk=news_id).update(
												title=title,
												desc=desc,
			                                    thumbnail=thumbnail,
												content=content,
												category=category)
			return restful.ok()
		else:
			return restful.paramserror(message=form.get_errors())

@xfz_perms_change_required
@require_POST
def del_news(request):
	news_id = request.POST.get('news_id')
	try:
		News.objects.get(pk=news_id).delete()
		return restful.ok()
	except News.DoesNotExist:
		return restful.paramserror(message='该新闻不存在！')

@method_decorator(xfz_perms_change_required, name='dispatch')
class NewsCategoryView(View):
	def get(self, request):
		# from django.db.models import Count
		# category.news_set.all().aggregate(Count('id'))
		categories = NewsCategory.objects.all()
		return render(request, 'cms/news_category.html', {'categories':categories})

@xfz_perms_change_required
@require_POST
def add_category(request):
	category = request.POST.get('category')
	if category:
		exists = NewsCategory.objects.filter(name=category)
		if not exists:
			NewsCategory.objects.create(name=category)
			return restful.ok()
		else:
			return restful.paramserror(message="分类名已存在!")
	else:
		return restful.paramserror(message="请输入分类名!")

@xfz_perms_change_required
@require_POST
def edit_category(request):
	form = EditCategory(request.POST)
	if form.is_valid():
		pk = request.POST.get('pk')
		category = request.POST.get('category')
		try:
			NewsCategory.objects.filter(pk=pk).update(name=category)
			return restful.ok()
		except:
			message = "该分类不存在！"
			return restful.paramserror(message=message)
	else:
		return restful.paramserror("参数错误！")

@xfz_perms_change_required
@require_POST
def del_category(request):
	pk = request.POST.get('pk')
	try:
		category = NewsCategory.objects.get(pk=pk)
		category.delete()
		return restful.ok()
	except NewsCategory.DoesNotExist:
		message = "该分类不存在！"
		return restful.paramserror(message=message)

xfz_perms_change_required
@require_POST
def upload_file(request):
	file = request.FILES.get('file')
	name = file.name
	with open(os.path.join(settings.MEDIA_ROOT,name), 'wb') as fp:
		for chunk in file.chunks():
			fp.write(chunk)
	url = request.build_absolute_uri(settings.MEDIA_URL + name)
	return restful.result(data={'url':url})

@xfz_perms_change_required
def banners(request):
	return render(request,'cms/banner.html')

@xfz_perms_change_required
def banner_add(request):
	form = BannerForm(request.POST)
	if form.is_valid():
		priority = form.cleaned_data.get("priority")
		image_url = form.cleaned_data.get("image_url")
		link_to = form.cleaned_data.get("link_to")
		banner = Banner.objects.create(priority=priority, image_url=image_url, link_to=link_to)
		return restful.result(data={"banner_id": banner.pk})
	else:
		message = form.get_errors()
		return restful.paramserror(message=message)

xfz_perms_change_required
@require_POST
def banner_del(request):
	pk = request.POST.get('banner_id')
	try:
		banner = Banner.objects.get(pk=pk)
		banner.delete()
		return restful.ok()
	except Banner.DoesNotExist:
		message = "该轮播图不存在！"
		return restful.paramserror(message=message)

@xfz_perms_change_required
@require_POST
def banner_edit(request):
	form = editBannerForm(request.POST)
	if form.is_valid():
		pk = form.cleaned_data.get('pk')
		priority = form.cleaned_data.get("priority")
		image_url = form.cleaned_data.get("image_url")
		link_to = form.cleaned_data.get("link_to")
		Banner.objects.filter(pk=pk).update(priority=priority, image_url=image_url, link_to=link_to)
		return restful.ok()
	else:
		message = form.get_errors()
		return restful.paramserror(message)

@xfz_perms_change_required
def banner_list(request):
	banners = Banner.objects.all()
	serializer = BannerSerializer(banners, many=True)
	data = serializer.data
	return restful.result(data=data)

@method_decorator(xfz_perms_change_required, name='dispatch')
class NewsListView(View):
	def get(self,request):
		start = request.GET.get('start-time')
		end = request.GET.get('end-time')
		title = request.GET.get('title')
		category_id = int(request.GET.get('category', 0))
		around_count = 2
		page = int(request.GET.get('page',1))
		newses = News.objects.select_related('category', 'author')
		if start or end:
			if start:
				start_date = datetime.strptime(start,'%Y/%m/%d')
			else:
				start_date = datetime(year=2019, month=10, day=1)
			if end:
				end_date = datetime.strptime(end,'%Y/%m/%d')
			else:
				end_date = datetime.today()
			newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))
		if title:
			newses = newses.filter(title__icontains=title)
		if category_id:
			newses = newses.filter(category=category_id)

		paginator = Paginator(newses, around_count)
		page_obj = paginator.page(page)
		context_data = self.get_pagination_data(paginator, page_obj, around_count)
		context = {
			'categorys': NewsCategory.objects.all(),
			'news_list': page_obj.object_list,
			'url_query': '&' + parse.urlencode({
				'start-time': start or '',
				'end-time': end or '',
				'title': title or '',
				'category': category_id
			})
		}
		context.update(context_data)
		return render(request, 'cms/search_news.html', context=context)

	def post(self,request):
		pass

	def get_pagination_data(self, paginator, page_obj, around_count=5):
		current_page = page_obj.number
		num_pages = paginator.num_pages
		left_has_more = False
		right_has_more = False

		# 显示左边页码
		if current_page <= around_count + 2:
			left_pages = range(1, current_page)
		else:
			left_has_more = True
			left_pages = range(current_page-around_count, current_page)

		# 显示右边页码
		if current_page + around_count >= num_pages:
			right_pages = range(current_page+1, num_pages+1)
		else:
			right_has_more = True
			right_pages = range(current_page+1, current_page+around_count+1)
		return {
		 'page_obj': page_obj,
         'left_pages': left_pages,
         'right_pages': right_pages,
         'current_page': current_page,
         'around_count': around_count,
         'left_has_more': left_has_more,
         'right_has_more': right_has_more,
         'num_pages': num_pages
      }

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock %} | cms</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static "adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "adminlte/bower_components/font-awesome/css/font-awesome.min.css" %}">
  <link rel="stylesheet" href="{% static "adminlte/dist/css/AdminLTE.min.css" %}">
  <link rel="stylesheet" href="{% static "adminlte/dist/css/skins/_all-skins.min.css" %}">
  <link rel="stylesheet" href="{% static "adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" %}">
  <link rel="stylesheet" href="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.css">
  <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
  <script src="{% static "adminlte/bower_components/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "adminlte/bower_components/jquery-ui/jquery-ui.min.js" %}"></script>
  <script>
    $.widget.bridge('uibutton', $.ui.button);
  </script>
  <script src="{% static "js/auth_ajax.min.js" %}"></script>
  <script src="{% static "adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
  <script src="{% static "adminlte/dist/js/adminlte.min.js" %}"></script>
  <script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>
  <script src="{% static "js/message.min.js" %}"></script>
  {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    <a href="#" class="logo">
      <span class="logo-mini"><b>CMS</b></span>
      <span class="logo-lg"><b>CMS管理平台</b></span>
    </a>
    <nav class="navbar navbar-static-top">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"></a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static "adminlte/dist/img/user2-160x160.jpg" %}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <img src="{% static "adminlte/dist/img/user2-160x160.jpg" %}" class="img-circle" alt="User Image">
                <p>
                  Python web学习者
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">个人中心</a>
                </div>
                <div class="pull-right">
                  <a href="{% url "xfzauth:logout_view" %}" class="btn btn-default btn-flat">注销登录</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
 <!-- 侧边栏处-->
  <aside class="main-sidebar">
    <section class="sidebar">
      <!-- 搜索框 -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- 侧边栏-->
      <ul class="sidebar-menu" data-widget="tree">
         <li class="active">
          <a href="/">
            <i class="fa fa-home"></i> <span>首页</span>
          </a>
        </li>
         {% if perms.news.change_news %}
         <li class="header">新闻管理</li>
         <li>
          <a href="{% url "cms:write_news" %}">
            <i class="fa fa-pencil-square-o"></i> <span>发布新闻</span>
          </a>
        </li>
         <li>
          <a href="{% url "cms:news_category" %}">
            <i class="fa fa-tags"></i> <span>新闻分类</span>
          </a>
        </li>
          <li>
          <a href="{% url "cms:banners" %}">
            <i class="fa fa-image"></i> <span>轮播图管理</span>
          </a>
        </li>
          <li>
          <a href="{% url "cms:news_list" %}">
            <i class="fa fa-folder-open-o"></i> <span>新闻管理</span>
          </a>
        </li>
      {% endif %}
      {% if perms.course.change_course %}
          <li class="header">课程管理</li>
          <li>
          <a href="{% url "cms:publish_course" %}">
            <i class="fa fa-tv"></i> <span>发布课程</span>
          </a>
       {% endif %}
          {% if request.user.is_superuser %}
          <li class="header">权限管理</li>
          <li>
          <a href="{% url "cms:staff_view" %}">
            <i class="fa fa-group"></i> <span>员工管理</span>
          </a>
          </li>
          {% endif %}
      </ul>
    </section>

  </aside>

  <!-- 主页正文内容-->
  <div class="content-wrapper">
    <section class="content-header">
        {% block content-header %}{% endblock %}
    </section>
    <section class="content">
        {% block content %}{% endblock %}
    </section>
  </div>
  <footer class="main-footer">
    <strong>CMS管理平台</strong>
  </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>新闻发布</h1>
{% endblock %}

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}新闻分类{% endblock %}

{% block head %}
    <script src="{% static "js/news_category.min.js" %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
          <div class="box box-primary">
              <div class="box-header">
                  <button type="button" id="category-add-btn" class="btn btn-primary pull-right">添加分类</button>
              </div>
              <div class="box-body">
                  <table class="table table-hover">
                    <thead>
                        <tr role="row">
                        <th>分类名</th>
                        <th>新闻数量</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                            <tr role="row" data-pk="{{ category.id }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>20</td>
                                <td>
                                    <button type="button" class="btn btn-warning btn-xs edit-btn">编辑</button>
                                    <button type="button" class="btn btn-danger btn-xs del-btn">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                  </tbody>
                  </table>
              </div>
          </div>
        </div>
      </div>
{% endblock %}

front/templates/cms/search_news.html
{% extends 'cms/base.html' %}
{% load my_filter %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/news_search/news-search.min.css" %}">
    <link rel="stylesheet" href="{% static "adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" %}">
    <script src="{% static "adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js" %}"></script>
    <script src="{% static "js/news_list.min.js" %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻管理</h1>
{% endblock %}

{% block content %}
     <div class="row">
        <div class="col-md-12">
          <div class="box box-primary">
              <div class="box-header">
                  <form action="{% url "cms:news_list" %}" method="get" class="form-inline" >
                      <div class="form-group">
                          <label for="start-time">时间:</label>
                          <input type="text" class="form-control " placeholder="开始时间" id="startpicker" name="start-time" readonly>
                          <span>--</span>
                          <input type="text" class="form-control" placeholder="结束时间" id="endpicker" name="end-time" readonly>
                      </div>
                      <div class="form-group header-group">
                          <label for="title">标题:</label>
                          <input type="text" class="form-control" placeholder="标题" name="title">
                      </div>
                      <div class="form-group header-group">
                          <label for="category">分类:</label>
                            <select class="form-control" name="category">
                                <option value="0">所有分类</option>
                                {% for category in categorys %}
                                    <option value={{ category.id }}>{{ category.name }}</option>
                                {% endfor %}
                            </select>
                      </div>
                      <div class="form-group header-search">
                          <input class="btn  btn-primary" type="submit" value="查询">
                      </div>
                      <a href="{% url "cms:news_list" %}" class="header-clear">清除查询</a>
                  </form>
              </div>
              <div class="box-body">
                  <table class="table table-hover">
                    <thead>
                        <tr role="row">
                        <th>标题</th>
                        <th>新分类</th>
                        <th>发布时间</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for news in news_list %}
                            <tr role="row" data-news-id="{{ news.id }}">
                                <td><a href="{% url "news:news_detail" news_id=news.pk %}" target="_blank">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time|time_format}}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <a href="{% url "cms:edit_news" %}?news_id={{ news.id }}"><button type="button" class="btn btn-warning btn-xs edit-btn">编辑</button></a>
                                    <button type="button" class="btn btn-danger btn-xs del-btn" data-news-id="{{ news.id }}" id="delete-btn">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                  </tbody>
                  </table>
              </div>
              <div class="box-footer">
                <p class="pull-left">第{{ current_page }}页/总共{{ num_pages }}页</p>
                <ul class="pagination pull-right">
                    {% if page_obj.has_previous %}
                        <li><a href="{% url "cms:news_list" %}?page={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                    {% endif %}

                {# 左边页码 #}
                    {% if left_has_more %}
                        <li><a href="?page=1">1</a></li>
                        <li class="disabled"><a href="javascript:void(0);">...</a></li>
                    {% endif %}
                    {% for left_page in left_pages %}
                        <li><a href="?page={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                    {% endfor %}

                {# 当前页 #}
                 <li class="active"><a href="?page={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                {# 右边页码 #}
                {% for right_page in right_pages %}
                    <li><a href="?page={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                    {% endfor %}
                {% if right_has_more %}
                        <li class="disabled"><a href="javascript:void(0);">...</a></li>
                        <li><a href="?page={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                {% endif %}

                {# 下一页 #}
                {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                {% else %}
                        <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                {% endif %}
                </ul>
              </div>
          </div>
        </div>
      </div>
{% endblock %}

front/templates/cms/staff.html
{% extends 'cms/base.html' %}

{% block head %}{% endblock %}

{% block content-header %}
    <h1>员工管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <a href="{% url "cms:staff_add_view" %}"><button class="btn btn-info pull-right">添加员工</button></a>
                </div>
                <div class="box-body">
                    <table class="table table-hover">
                        <thead>
                        <tr role="row">
                            <th>用户名</th>
                            <th>手机号</th>
                            <th>所属分组</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                        <tbody>
                            {% for staff in staffs %}
                                <tr role="row">
                                    <td>{{ staff.username }}</td>
                                    <td>{{ staff.telephone }}</td>
                                    {% if staff.is_superuser %}
                                        <td>超级管理员</td>
                                    {% else %}
                                        <td>
                                            {% for group in staff.groups.all %}
                                                {{ group.name }}
                                                <span>/</span>
                                            {% endfor %}
                                        </td>
                                    {% endif %}
                                    <td>
                                        <button type="button" class="btn btn-warning btn-xs edit-btn">编辑</button>
                                        <button type="button" class="btn btn-danger btn-xs del-btn">删除</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
                <div class="box-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/staff_add.html
{% extends 'cms/base.html' %}

{% block head %}{% endblock %}

{% block content-header %}
    <h1>添加员工</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <form action="{% url "cms:staff_add_view" %}" method="post">
                    {% csrf_token %}
                    <div class="box-header"></div>
                    <div class="box-body">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="form-group">
                        <label for="">手机号:</label>
                        <input type="text" class="form-control" id="telephone" name="telephone">
                    </div>
                    <span>选择分组</span>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                {% for group in groups %}
                                    <input type="checkbox" name="group" value="{{ group.pk }}">{{ group.name }}
                                {% endfor %}
                            </label>
                        </div>
                    </div>
                </div>
                    <div class="box-footer">
                   <button type="submit" class="btn btn-primary pull-right">添加</button>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}