apps/cms/urls.py
from django.urls import path
from . import views
from . import course_views, straff_views

app_name = 'cms'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('write_news/', views.WirteNewsView.as_view(), name="write_news"),
    path('edit_news/', views.EditNewsView.as_view(), name="edit_news"),
    path('del_news/', views.del_news, name="del_news"),
    path('news_category/', views.NewsCategoryView.as_view(), name="news_category"),
    path('add_category/', views.add_category, name="add_category"),
    path('edit_category/', views.edit_category, name="edit_category"),
    path('del_category/', views.del_category, name="del"),
    path('upload/', views.upload_file, name="upload_file"),
    path('banner/', views.banners, name="banners"),
    path('banner_add/', views.banner_add, name="banner_add"),
    path('banner_list/', views.banner_list, name="banner_list"),
    path('banner_del/', views.banner_del, name="banner_del"),
    path('banner_edit/', views.banner_edit, name="banner_edit"),
    path('news_list/', views.NewsListView.as_view(), name="news_list"),
]

urlpatterns += [
    path('publish_course/', course_views.PublishCourseView.as_view(), name="publish_course"),
]

urlpatterns += [
    path('staff_view/', straff_views.StaffView.as_view(), name="staff_view"),
    path('staff_add_view/', straff_views.StaffAddView.as_view(), name="staff_add_view"),
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'
urlpatterns = [
    path('login/', views.login_view, name="login_view"),
    path('logout/', views.logout_view, name="logout_view"),
    path('signup/', views.signup_view, name="signup_view"),
    # 登录页面验证码图片请求
    path('get_valid_img/', views.GetValidImg.as_view(), name='get_valid_img'),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('news/', include("apps.news.urls")),
    path('cms/', include("apps.cms.urls")),
    path('account/', include("apps.xfzauth.urls")),
    path('course/', include("apps.course.urls")),
    path('controller/', include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1414195_ycfnhgcx9fc.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1414195_ztpmnlu0rn.css">
    <link rel="stylesheet" href="{% static "css/auth/auth.min.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/message.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/auth_ajax.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/auth.min.js" %}"></script>


    {% block head %}{% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo-box">
                <a href="/"></a>
            </div>
            <ul class="nav">
                <li class="active"><a href="#">创投咨讯</a></li>
                <li><a href="#">创业课堂</a></li>
                <li><a href="#">付费资讯</a></li>
                <li><a href="#">搜索</a></li>
            </ul>
            <div class="auth-box">
                {% if request.user.is_authenticated %}
                    <div class="hover-user">
                        <i class="iconfont icon-person"></i>
                        <span class="login-user">{{ request.user.username }}</span>
                        <div class="dis">
                            {% if request.user.is_staff or request.user.is_superuser%}
                                <a href="{% url 'cms:index' %}">管理后台</a>
                            {% endif %}
                            <a href="{% url 'xfzauth:logout_view' %}">退出登录</a>
                        </div>
                    </div>
                {% else %}
                    <i class="iconfont icon-person"></i>
                    <a href="#" id="sigin">登录</a> /
                    <a href="#" id="signup">注册</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% block main %}{% endblock %}
    <footer class="footer">
        <div class="top-group">
            <div class="top-main">
                <div class="logo-box"></div>
                <div class="detail-group">
                    <div class="line1">
                        <ul class="links">
                                <li><a href="#">关于小饭桌</a></li>
                                <li><a href="#">小饭桌创业课堂</a></li>
                                <li><a href="#">凡创资本</a></li>
                                <li><a href="#">凡卓资本</a></li>
                            </ul>
                        <div class="about-us">
                            <span class="title">关注我们：</span>
                            <ul class="social">
                                <li class="weixin">
                                    <div class="wx-qrcode"></div>
                                    <span class="text-weixin">小饭桌</span>
                                </li>
                                <li class="gzh"><span class="text-gzh">小饭桌创业课堂</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="line2">
                        <p class="address">地址：北京市朝阳区东三环北路38号院泰康金融大厦</p>
                        <p class="phonenum">融资服务： bp@xfz.cn 商务合作： bd@xfz.cn</p>
                    </div>
                </div>
            </div>

        </div>
        <div class="down-footer-group">
            <div class="record-group">
                <p>©2019 北京子木投资顾问有限公司 京ICP备15051289号|增值电信业务经营许可证：京B2-20170574</p>
            </div>
        </div>
    </footer>
    <div class="mask-wrapper" id="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span id="close" class="close-btn close icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                <div class="sigin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" name="telephone" class="form-control" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="password" name="password" class="form-control" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remember">
                                <input type="checkbox" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn submit-siginbtn" value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="sigup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript: void(0);" class="switch">立即登录></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                           <input type="text" name="telephone" class="form-control" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                           <input type="text" name="username" class="form-control" placeholder="请输入用户名">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" name="img_captcha" class="form-control" placeholder="请输入验证码">
                            </div>
                            <div class="input-group-addon">
                                <img src="{% url 'xfzauth:get_valid_img' %}" alt="图形验证码" class="img-captcha">
                            </div>
                        </div>
                        <div class="input-group">
                           <input type="password" name="password1" class="form-control" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                           <input type="password" name="password2" class="form-control" placeholder="确认密码">
                        </div>
                        <!--
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" name="sms_captcha" class="form-control" placeholder="请输入验证码">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms-captcha-btn">发送验证码</span>
                            </div>
                        </div>
                        -->
                        <div class="input-group">
                            <input type="submit" class="submit-btn submit-signupbtn" value="立即注册">
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</body>
</html>

front/templates/base/sidebar.html
<div class="sidebar-wrapper">
                <div class="title-group">
                    <span class="title">在线课堂</span>
                    <a href="#" class="more">更多</a>
                </div>
                <div class="advertis"><a href=""><img src="https://static-image.xfz.cn/1554346383_8.png" alt=""></a></div>
                <div class="title-group"><span class="title">关注小饭桌</span></div>
                <div class="focus-group">
                    <div class="left-focus">
                        <ul>
                            <li class="zhihu"><a href="#" target="_blank">小饭桌创业课堂</a></li>
                            <li class="weibo"><a href="#" target="_blank">小饭桌创业课堂</a></li>
                            <li class="toutiao"><a href="#" target="_blank">小饭桌</a></li>
                        </ul>
                    </div>
                    <div class="right-focus">
                        <p class="desc">扫码关注小饭桌微信公众平台</p>
                    </div>
                </div>
                <div class="title-group">
                    <span class="title">热门推荐</span>
                </div>
                <div class="hot-news-group">
                    <ul class="hot-list">
                        <li>
                            <div class="left-group">
                                <p class="desc"><a href="#">他苦熬印度短视频三年，在下沉市场避开抖音竞争，靠趣头条模式获客融资千万</a></p>
                                <div class="more">
                                    <span class="category"><a href="#">热点</a></span>
                                    <span class="pub-time">09月20日</span>
                                </div>
                            </div>
                            <div class="right-group">
                                <img src="https://static-image.xfz.cn/1568719627_836.png-website.news.list" alt="">
                            </div>
                        </li>

                         <li>
                            <div class="left-group">
                                <p class="desc"><a href="#">他苦熬印度短视频三年，在下沉市场避开抖音竞争，靠趣头条模式获客融资千万</a></p>
                                <div class="more">
                                    <span class="category"><a href="#">热点</a></span>
                                    <span class="pub-time">09月20日</span>
                                </div>
                            </div>
                            <div class="right-group">
                                <img src="https://static-image.xfz.cn/1568719627_836.png-website.news.list" alt="">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>